### ISSUE TITLE
How can we get this to work if SSL is enabled?

### ISSUE THREAD

**Issue by jamonroad** [AlexxIT/MediaExtractorPro#3]
Greetings,
This was working great prior to configuring DuckDNS with SSL. Now it will only play non-playlist Youtube files, it will no longer play playlists.

Is there a way to get it to work with SSL activated in Home Assistant?

**Comment by AlexxIT** [comment]
Have you configured Hass local and Hass global IP address in yaml or GUI?

**Comment by jamonroad** [comment]
Thank you for your reply.

Hass local and Hass global IP address are configured in the
configuration.yaml and GUI as follows:
[image: HassioSSL1.png]

[image: HassioSSL2.png]

**Comment by jamonroad** [comment]
Here is the Hassio error when trying to play a playlist:
*************************************************************************************

Logger: homeassistant.core
Source: custom_components/media_extractor/__init__.py:99
First occurred: 9:13:40 AM (1 occurrences)
Last logged: 9:13:40 AM
Error executing service: <ServiceCall media_extractor.play_media
(c:2440aa972f1816feee164bf4c7773a25):
entity_id=media_player.living_room_sound_bar, media_content_id=
https://www.youtube.com/watch?v=iWza_On7ajs&list=PLzVnkUWsi7RO2DvZB3VvIhR3kf9T4BBjl,
media_content_type=music>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1461, in
catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in
_execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_extractor/__init__.py", line
99, in play_media
    url = media['url']
KeyError: 'url'

**Comment by AlexxIT** [comment]
Try to check other media services. Maybe problem with YouTube. They continiosly change logic with getting direct video link.

**Comment by jamonroad** [comment]
I'll check, but *note* that it was working perfectly prior to configuring
SSL a few days ago.

**Comment by AlexxIT** [comment]
Your error don't depend on SSL
